apiVersion: v1
kind: Service
metadata:
  name: flask-microservice
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30002
 selector:
  app: flask-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-microservice
spec:
  selector:
    matchLabels:
      app: flask-ms
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-ms
    spec:
      containers:
      - name: flask-ms
        imagePullPolicy: Always
        image: 200okdocker/flask-service
        ports:
        - containerPort: 5000